apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "AppMonitoring.fullname" . }}
  labels:
    {{- include "AppMonitoring.labels" . | nindent 4 }}
spec:
  endpoints:
    - port: http
  selector:
    matchLabels:
      {{- include "AppMonitoring.labels" . | nindent 6 }}